# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'    
    - run: npm install
    - run: echo ${GITHUB_WORKSPACE} 
    - run: npm run build 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:    
        name: artifact    
        path: /home/runner/work/HotelSearchServiceFrontEnd/HotelSearchServiceFrontEnd/build
        
        if-no-files-found: warn
        retention-days: 2
    
    
  deploy:
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_access_key_secret }}
        aws-region: us-east-1
    - name: Workspace value
      run: echo ${GITHUB_WORKSPACE}
    - name: show contents
      run: ls ${GITHUB_WORKSPACE}
    - name: Retrieve artifacts
      uses: actions/download-artifact@v2
      with:
          name: artifact
          path: /home/runner/work/HotelSearchServiceFrontEnd/HotelSearchServiceFrontEnd/build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ${GITHUB_WORKSPACE}/build s3://hotelsearch.pavithraavasudevan.com.d0e --delete
